export const filters = [
  {
    title: "Líneas",
    name: "lineas",
    options: [
      "Arquitectónica",
      "Industrial",
      "Automotriz",
      "Metalmecánica",
      "Pisos Epoxicos",
      "Madera",
      "Demarcación Vial",
      "Especiales",
    ],
  },
  {
    title: "Acabados",
    name: "acabados",
    options: [
      "Brillante-Mate",
      "Mate",
      "Satin",
      "Semi-Brillante",
      "Semi-Mate",
      "Transparente",
    ],
  },
  {
    title: "Ambiente Exterior",
    name: "ambiente_exterior",
    options: [
      "Canchas",
      "Carreteras",
      "Decks",
      "Estructuras Metálicas",
      "Fachada",
      "Muro",
      "Parqueadero",
      "Terraza",
    ],
  },
  {
    title: "Ambiente Interior",
    name: "ambiente_interior",
    options: [
      "Baño",
      "Cocina",
      "Consultorios",
      "Comedor",
      "Habitación",
      "Sala",
      "Tumbados",
    ],
  },
  {
    title: "Superficies",
    name: "superficies",
    options: [
      "Acero",
      "Asfalto",
      "Bloques",
      "Cemento",
      "Césped",
      "Cielos Rasos - Tumbados",
      "Estuco",
      "Fachaleta",
      "Fibrocemento",
      "Gypsum",
      "Hierro",
      "Losas",
      "Madera",
      "Metales Ferrosos",
      "Metales No Ferrosos",
      "Paredes",
      "Piedra",
      "Tejas",
    ],
  },
  {
    title: "Tipo de Producto",
    name: "tipo_producto",
    options: [
      "Esmaltes",
      "Especialidades",
      "Impermeabilizantes",
      "Intumescentes",
      "Látex",
      "Light Industrial",
      "Línea Madera",
      "Preparación de superficie",
      "Señalización Vial",
    ],
  },
];
